// Vsi članki na strani. Avtorji so izmišljeni (demo), fotografije so z Unsplasha.
window.ZON_ARTICLES = [
  {
    slug: "sezona-na-vrhuncu",
    title: "Sezona na vrhuncu: Na eni strani že 40 let, na drugi pot pod zemljo",
    tags: ["Aktualno", "Hrastnik", "Litija", "Šport", "Trbovlje", "Zagorje"],
    author: "Ana Kovač",
    date: "02. 10. 2026",
    image: "img/sezona.jpg",
    credit: "MChe Lee / Unsplash",
    featured: true,
  },
  {
    slug: "avtomobil-za-300-evrov",
    title: "Avtomobil, vreden več kot 3.000 evrov, je kupec odpeljal le za 300 in izginil",
    tags: ["Aktualno", "Hrastnik", "Kronika", "Litija", "Trbovlje", "Zagorje"],
    author: "Uredništvo ZON",
    date: "02. 10. 2026",
    image: "img/avtomobil.jpg",
    credit: "Linus Belanger / Unsplash",
  },
  {
    slug: "posebna-postelja-v-zasavju",
    title: "Zaradi posebne postelje v Zasavje prihajajo ljudje iz vse Slovenije",
    tags: ["Aktualno", "Zagorje"],
    author: "Ana Kovač",
    date: "02. 10. 2026",
    image: "img/postelja.jpg",
    credit: "Francesca Tosolini / Unsplash",
  },
  {
    slug: "pri-copu-gozd-na-krozniku",
    title: "Pri Čopu bo gozd končal na krožniku",
    tags: ["Aktualno", "Hrastnik", "Trbovlje", "Zagorje"],
    author: "Tina Zupan",
    date: "02. 10. 2026",
    image: "img/cop.jpg",
    credit: "Pylyp Sukhenko / Unsplash",
  },
  {
    slug: "dva-milijona-za-litijo",
    title: "Dobra dva milijona evrov bo romalo v Litijo",
    tags: ["Aktualno", "Litija"],
    author: "Ana Kovač",
    date: "02. 10. 2026",
    image: "img/litija.jpg",
    credit: "Max Böhme / Unsplash",
  },
];
